In [1]:
import numpy as np

In [3]:
arr = np.arange(5)

In [4]:
arr

array([0, 1, 2, 3, 4])

In [6]:
np.save('myarray',arr)

In [7]:
arr = np.arange(10)

In [8]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.load('myarray.npy')

array([0, 1, 2, 3, 4])

In [11]:
arr1 = np.load('myarray.npy')

In [12]:
arr1

array([0, 1, 2, 3, 4])

In [13]:
arr2 = arr

In [14]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.savez('ziparray.npz',x=arr1,y=arr2)

In [16]:
archive_array = np.load('ziparray.npz')

In [18]:
archive_array['x']

array([0, 1, 2, 3, 4])

In [19]:
archive_array['y']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
arr = np.array([[1,2,3],[4,5,6]])

In [22]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
np.savetxt('mytxtarray.txt',arr,delimiter=',')

In [25]:
np.loadtxt('mytxtarray.txt',delimiter=',')

array([[1., 2., 3.],
       [4., 5., 6.]])