In [1]:
import numpy as np

In [2]:
5/2

2.5

In [3]:
arr1 = np.array([[1,2,3,4],[8,9,10,11]])

In [4]:
arr1

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

In [5]:
arr1*arr1

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

In [6]:
arr1-arr1

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [7]:
1/arr1

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.125     , 0.11111111, 0.1       , 0.09090909]])

In [8]:
arr1**3

array([[   1,    8,   27,   64],
       [ 512,  729, 1000, 1331]], dtype=int32)

In [9]:
arr1 ** 3

array([[   1,    8,   27,   64],
       [ 512,  729, 1000, 1331]], dtype=int32)

In [10]:
np.array(arr1).shape

(2, 4)

In [11]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [12]:
np.array(4,40,3)

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [13]:
np.array(4,40,2)

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [14]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])