In [1]:
import numpy as np

In [2]:
my_list1 = [1,2,3,4]

In [3]:
my_array1 = np.array(my_list1)

In [4]:
my-array1

NameError: name 'my' is not defined

In [5]:
my_array1

array([1, 2, 3, 4])

In [6]:
my_list2 = [11,12,13,14]

In [7]:
my_lists = [my_list1,my_list2]

In [8]:
my_array2 = np.array(my_lists)

In [9]:
my_array2

array([[ 1,  2,  3,  4],
       [11, 12, 13, 14]])

In [10]:
my_array2.shape

(2, 4)

In [11]:
my_array2.dtype

dtype('int32')

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
my_zeros_arrays = np.zeros(5)

In [14]:
my_zeros_arrays.dtype

dtype('float64')

In [15]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
np.empty(5)

array([2.12199579e-314, 2.22517741e-307, 3.37940902e-321, 1.09494983e-311,
       2.78143569e-307])

In [17]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [19]:
np.arange(5,50,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])

In [20]:
np.arange.shape

AttributeError: 'builtin_function_or_method' object has no attribute 'shape'

In [21]:
np.arange(5,50,2).shape

(23,)