In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[0:7] = 100

In [8]:
arr

array([100, 100, 100, 100, 100, 100, 100,   7,   8,   9,  10])

In [9]:
arr = np.arange(0,11)

In [10]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
arr = np.arange(0,50,2)

In [12]:
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [13]:
slice_of_arr = arr[0,6]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [14]:
slice_of_arr = [0:6]

SyntaxError: invalid syntax (<ipython-input-14-7c3139ce5696>, line 1)

In [15]:
slice_of_arr = arr[0:6]

In [16]:
slice_of_arr

array([ 0,  2,  4,  6,  8, 10])

In [17]:
slice_of_arr = 99

In [18]:
slice_of_arr

99

In [19]:
slice_of_arr[:] = 99

TypeError: 'int' object does not support item assignment

In [20]:
arr = np.arange(0,11)

In [21]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
slice_of_arr = arr[0:6]

In [23]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [24]:
slice_of_arr[:] = 99

In [25]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [26]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [27]:
arr_copy = np.copy()

TypeError: _copy_dispatcher() missing 1 required positional argument: 'a'

In [28]:
arr_copy = arr.copy()

In [29]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [54]:
arr_2d = np.array(([5,10,20],[15,25,30],[35,40,50]))

In [55]:
arr_2d

array([[ 5, 10, 20],
       [15, 25, 30],
       [35, 40, 50]])

In [56]:
arr_2d[0]

array([ 5, 10, 20])

In [57]:
arr_2d[1:,:0]

array([], shape=(2, 0), dtype=int32)

In [34]:
arr_2d[2:,:1]

array([[30]])

In [35]:
arr_2d[1:,:2]

array([[15, 25],
       [30, 40]])

In [36]:
arr_2d[1:,1:]

array([[25, 30],
       [40, 50]])

In [37]:
arr_2d[2]

array([30, 40, 50])

In [38]:
arr_2d = np.zeros((10,10))

In [39]:
arr_2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [40]:
arr_length = arr_2d.shape[1]

In [41]:
arr_length

10

In [66]:
for i in range(arr_length):
    arr_2d[i]=1
    arr_2d

IndexError: index 3 is out of bounds for axis 0 with size 3

In [51]:
arr_2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [52]:
arr_2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [58]:
arr2d = np.array(([1,2,3],[4,5,6],[7,8,9]))

In [59]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
arr2d[0:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [61]:
arr2d[:0,:2]

array([], shape=(0, 2), dtype=int32)

In [62]:
arr2d[:1,:2]

array([[1, 2]])

In [63]:
arr2d[:1,:1]

array([[1]])

In [64]:
arr2d[1:,1:]

array([[5, 6],
       [8, 9]])

In [65]:
arr2d[2:,2:]

array([[9]])