In [1]:
import numpy as np

In [2]:
arr = np.arange(11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.sqrt.(arr)

SyntaxError: invalid syntax (<ipython-input-4-bcbc4cbac987>, line 1)

In [5]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [6]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [7]:
A = np.random.randn(10)

In [8]:
A

array([ 0.31747145, -0.29713131, -0.2396151 ,  0.53526691,  1.00452644,
        0.19282238, -0.78600012, -0.83725888, -0.49122468,  0.04740795])

In [9]:
B = np.random.randn(10)

In [10]:
B

array([-0.17012083, -1.44600508,  0.26001548,  0.50003013, -0.31669726,
       -0.37273555, -0.7523141 , -0.25481197,  0.53966439, -0.36311009])

In [11]:
#Binary Functions
np.add(A,B)

array([ 0.14735062, -1.74313639,  0.02040038,  1.03529704,  0.68782918,
       -0.17991317, -1.53831422, -1.09207085,  0.04843971, -0.31570213])

In [12]:
np.maximum(A,B)

array([ 0.31747145, -0.29713131,  0.26001548,  0.53526691,  1.00452644,
        0.19282238, -0.7523141 , -0.25481197,  0.53966439,  0.04740795])

In [13]:
website = 'http://docs.scipy.org/doc/numpy/reference/ufuncs.hyml#available-ufuncs'
import webbrowser
webbrowser.open(website)

True

In [14]:
angles = np.array([0,30,45,60,90,180])

In [15]:
angles

array([  0,  30,  45,  60,  90, 180])

In [16]:
radians = np.deg2rad(angles)

In [17]:
radians

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633,
       3.14159265])

In [18]:
sinvalue = np.sin(angles)

In [19]:
sinvalue

array([ 0.        , -0.98803162,  0.85090352, -0.30481062,  0.89399666,
       -0.80115264])

In [20]:
sinvalue = np.sin(radians)

In [21]:
sinvalue

array([0.00000000e+00, 5.00000000e-01, 7.07106781e-01, 8.66025404e-01,
       1.00000000e+00, 1.22464680e-16])

In [22]:
weight = ([50,60,70,80,90])

In [23]:
print('mean weight of the student is: ')

mean weight of the student is: 


In [24]:
print(np.mean(weight))

70.0


In [26]:
print(np.percentile(weight,70))

78.0


In [27]:
weight = [99]

In [28]:
weight

[99]